### PR TITLE
Support jquery  2.X event for transition properties  

### PR DESCRIPTION
**Pull request by danielgranat**
Trying to use this module in my project, the transitionend event wasn't called with propertyName == 'Opacity'
After some debugging, I found that the function onOpacityTransitionEnd is getting jquery event, that does not contain propertyName. From googling i understand that this change was caused in JQuery 2.0, and was not yet addressed by JQuery.

I'm interested in hearing your thoughts on the modification i made.
Thanks!

### CODE REVIEW

**Comment by lugovsky** [comment]
Hey @danielgranat !

Thanks a lot for you PR! Could you please fix comment I made in your commit?

**Comment by lugovsky** [comment]
As well, what are you trying to achieve with that ng-disabled commit? Can't get the point. When you put disabled attribute on button. Clicking on it won't produce click event. 

Could you advice?

**Comment by danielgranat** [comment]
>  Could you please fix comment I made in your commit?

Sure i can. I was thinking that it's more readable this way, and the minified css already changes this to one line anyway. Will do that tomorrow.

> What are you trying to achieve with that ng-disabled commit?

Wasn't sure if to PR that as well. It does relevant to other people as well, but i am not sure that's the best solution.
The thing is i have a save button, which should be disabled when the form is not dirty.
After the first time i press save the button should be disabled, since it has ng-disabled="! form.$dirty". The problem is that after angular evaluates the ng-disabled expression, the progress-button code overrides this by setting it to enabled, only it does that not using angular, so angular has no effect anymore, since ng-disabled is not aware of the change.
After trying several ways that didn't work (like adding an attribute to ng-disabled from with the progress-button), i choose an approach that if the developer is already using ng-disabled on the button, then i leave it for him to controls the button enabled/disabled state.

Does it make sense?

**Comment by lugovsky** [comment]
Right now I don't think, that this solution for ng-disabled would be the best. When the two separate directives mess with single attribute it's not good and could produce bugs. I created separate issue #5 for this task: need to think about it a bit. Probably we will need to move away from using disabled attribute in the progress-button code

Thanks a lot for pointing it out

**Comment by danielgranat** [comment]
Thanks for looking in to this!
I feel the same way. My solution is a workaround, hens no PR for this issue :)
What about having a disabled transparent layer on top of the button, so it will prevent clicks from going to the button?

**Comment by lugovsky** [comment]
Too complex. We can still process clicks, but when the button will be in progress, we could just disable it on javascript layer. This would be just single condition inside onclick callback. The styles would require modification as well, but I guess this would worth it.

**Comment by danielgranat** [comment]
Yes, that will work very well. Is there a js indication that the click is in progress?

**Comment by lugovsky** [comment]
I don't remember actually. But if there isn't, that would be easy to add.

P.S. If you're planning to fix it on your own, please do it in a separate pull request. Either way, we can look at it tomorrow.

**Comment by danielgranat** [comment]
:+1:

**Pull request closed without merging**
